/**
 * Google Cloud Translation API supported languages.
 * Each entry: [BCP-47 code, English name, Native name]
 */
export const GOOGLE_TRANSLATE_LANGUAGES: readonly [
  code: string,
  english: string,
  native: string,
][] = [
  ["af", "Afrikaans", "Afrikaans"],
  ["sq", "Albanian", "Shqip"],
  ["am", "Amharic", "አማርኛ"],
  ["ar", "Arabic", "العربية"],
  ["hy", "Armenian", "Հայերեն"],
  ["as", "Assamese", "অসমীয়া"],
  ["ay", "Aymara", "Aymar"],
  ["az", "Azerbaijani", "Azərbaycan"],
  ["bm", "Bambara", "Bamanankan"],
  ["eu", "Basque", "Euskara"],
  ["be", "Belarusian", "Беларуская"],
  ["bn", "Bengali", "বাংলা"],
  ["bho", "Bhojpuri", "भोजपुरी"],
  ["bs", "Bosnian", "Bosanski"],
  ["bg", "Bulgarian", "Български"],
  ["ca", "Catalan", "Català"],
  ["ceb", "Cebuano", "Cebuano"],
  ["zh-CN", "Chinese (Simplified)", "中文（简体）"],
  ["zh-TW", "Chinese (Traditional)", "中文（繁體）"],
  ["co", "Corsican", "Corsu"],
  ["hr", "Croatian", "Hrvatski"],
  ["cs", "Czech", "Čeština"],
  ["da", "Danish", "Dansk"],
  ["dv", "Dhivehi", "ދިވެހި"],
  ["doi", "Dogri", "डोगरी"],
  ["nl", "Dutch", "Nederlands"],
  ["en", "English", "English"],
  ["eo", "Esperanto", "Esperanto"],
  ["et", "Estonian", "Eesti"],
  ["ee", "Ewe", "Eʋegbe"],
  ["fil", "Filipino", "Filipino"],
  ["fi", "Finnish", "Suomi"],
  ["fr", "French", "Français"],
  ["fy", "Frisian", "Frysk"],
  ["gl", "Galician", "Galego"],
  ["ka", "Georgian", "ქართული"],
  ["de", "German", "Deutsch"],
  ["el", "Greek", "Ελληνικά"],
  ["gn", "Guarani", "Avañe'ẽ"],
  ["gu", "Gujarati", "ગુજરાતી"],
  ["ht", "Haitian Creole", "Kreyòl Ayisyen"],
  ["ha", "Hausa", "Hausa"],
  ["haw", "Hawaiian", "ʻŌlelo Hawaiʻi"],
  ["he", "Hebrew", "עברית"],
  ["hi", "Hindi", "हिन्दी"],
  ["hmn", "Hmong", "Hmoob"],
  ["hu", "Hungarian", "Magyar"],
  ["is", "Icelandic", "Íslenska"],
  ["ig", "Igbo", "Igbo"],
  ["ilo", "Ilocano", "Ilokano"],
  ["id", "Indonesian", "Bahasa Indonesia"],
  ["ga", "Irish", "Gaeilge"],
  ["it", "Italian", "Italiano"],
  ["ja", "Japanese", "日本語"],
  ["jv", "Javanese", "Basa Jawa"],
  ["kn", "Kannada", "ಕನ್ನಡ"],
  ["kk", "Kazakh", "Қазақ"],
  ["km", "Khmer", "ខ្មែរ"],
  ["rw", "Kinyarwanda", "Ikinyarwanda"],
  ["gom", "Konkani", "कोंकणी"],
  ["ko", "Korean", "한국어"],
  ["kri", "Krio", "Krio"],
  ["ku", "Kurdish", "Kurdî"],
  ["ckb", "Kurdish (Sorani)", "سۆرانی"],
  ["ky", "Kyrgyz", "Кыргызча"],
  ["lo", "Lao", "ລາວ"],
  ["la", "Latin", "Latina"],
  ["lv", "Latvian", "Latviešu"],
  ["ln", "Lingala", "Lingála"],
  ["lt", "Lithuanian", "Lietuvių"],
  ["lg", "Luganda", "Luganda"],
  ["lb", "Luxembourgish", "Lëtzebuergesch"],
  ["mk", "Macedonian", "Македонски"],
  ["mai", "Maithili", "मैथिली"],
  ["mg", "Malagasy", "Malagasy"],
  ["ms", "Malay", "Bahasa Melayu"],
  ["ml", "Malayalam", "മലയാളം"],
  ["mt", "Maltese", "Malti"],
  ["mi", "Maori", "Te Reo Māori"],
  ["mr", "Marathi", "मराठी"],
  ["mni-Mtei", "Meiteilon (Manipuri)", "ꯃꯤꯇꯩꯂꯣꯟ"],
  ["lus", "Mizo", "Mizo ṭawng"],
  ["mn", "Mongolian", "Монгол"],
  ["my", "Myanmar (Burmese)", "မြန်မာ"],
  ["ne", "Nepali", "नेपाली"],
  ["no", "Norwegian", "Norsk"],
  ["ny", "Nyanja (Chichewa)", "Chichewa"],
  ["or", "Odia (Oriya)", "ଓଡ଼ିଆ"],
  ["om", "Oromo", "Afaan Oromoo"],
  ["ps", "Pashto", "پښتو"],
  ["fa", "Persian", "فارسی"],
  ["pl", "Polish", "Polski"],
  ["pt", "Portuguese", "Português"],
  ["pa", "Punjabi", "ਪੰਜਾਬੀ"],
  ["qu", "Quechua", "Runasimi"],
  ["ro", "Romanian", "Română"],
  ["ru", "Russian", "Русский"],
  ["sm", "Samoan", "Gagana Samoa"],
  ["sa", "Sanskrit", "संस्कृतम्"],
  ["gd", "Scots Gaelic", "Gàidhlig"],
  ["nso", "Sepedi", "Sepedi"],
  ["sr", "Serbian", "Српски"],
  ["st", "Sesotho", "Sesotho"],
  ["sn", "Shona", "ChiShona"],
  ["sd", "Sindhi", "سنڌي"],
  ["si", "Sinhala", "සිංහල"],
  ["sk", "Slovak", "Slovenčina"],
  ["sl", "Slovenian", "Slovenščina"],
  ["so", "Somali", "Soomaali"],
  ["es", "Spanish", "Español"],
  ["su", "Sundanese", "Basa Sunda"],
  ["sw", "Swahili", "Kiswahili"],
  ["sv", "Swedish", "Svenska"],
  ["tl", "Tagalog", "Tagalog"],
  ["tg", "Tajik", "Тоҷикӣ"],
  ["ta", "Tamil", "தமிழ்"],
  ["tt", "Tatar", "Татар"],
  ["te", "Telugu", "తెలుగు"],
  ["th", "Thai", "ไทย"],
  ["ti", "Tigrinya", "ትግርኛ"],
  ["ts", "Tsonga", "Xitsonga"],
  ["tr", "Turkish", "Türkçe"],
  ["tk", "Turkmen", "Türkmen"],
  ["ak", "Twi (Akan)", "Twi"],
  ["uk", "Ukrainian", "Українська"],
  ["ur", "Urdu", "اردو"],
  ["ug", "Uyghur", "ئۇيغۇرچە"],
  ["uz", "Uzbek", "Oʻzbek"],
  ["vi", "Vietnamese", "Tiếng Việt"],
  ["cy", "Welsh", "Cymraeg"],
  ["xh", "Xhosa", "IsiXhosa"],
  ["yi", "Yiddish", "ייִדיש"],
  ["yo", "Yoruba", "Yorùbá"],
  ["zu", "Zulu", "IsiZulu"],
] as const;

export type GoogleLanguageCode = (typeof GOOGLE_TRANSLATE_LANGUAGES)[number][0];
